# Generated by Django 6.0.3 on 2026-03-19 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RuParcelle',
            fields=[
                ('id_parcelle', models.IntegerField(primary_key=True, serialize=False)),
                ('identifiant', models.CharField(default='', max_length=50)),
                ('dep', models.IntegerField(default=0)),
                ('insee_com', models.IntegerField(default=0)),
                ('insee_com_absorbee', models.CharField(default='', max_length=50)),
                ('section', models.CharField(default='', max_length=50)),
                ('numero', models.CharField(default='', max_length=50)),
                ('m2_dgfip', models.IntegerField(default=0)),
                ('enclave', models.SmallIntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ru_parcelle',
                'indexes': [models.Index(fields=['identifiant'], name='idx_ru_parcelle_identifiant'), models.Index(fields=['insee_com'], name='idx_ru_parcelle_insee_com'), models.Index(fields=['section'], name='idx_ru_parcelle_section')],
            },
        ),
        migrations.CreateModel(
            name='RuAlignement',
            fields=[
                ('id_alignement', models.IntegerField(primary_key=True, serialize=False)),
                ('numero_debut', models.IntegerField(default=0)),
                ('adresse_debut', models.CharField(default='', max_length=50)),
                ('suffixe_un_debut', models.CharField(default='', max_length=50)),
                ('suffixe_2_debut', models.CharField(default='', max_length=50)),
                ('suffixe_3_debut', models.CharField(default='', max_length=50)),
                ('numero_fin', models.IntegerField(default=0)),
                ('adresse_fin', models.CharField(default='', max_length=50)),
                ('suffixe_un_fin', models.CharField(default='', max_length=50)),
                ('suffixe_2_fin', models.CharField(default='', max_length=50)),
                ('suffixe_3_fin', models.CharField(default='', max_length=50)),
                ('parite', models.SmallIntegerField(blank=True, null=True)),
                ('commune', models.IntegerField(default=0)),
                ('date', models.DateField(blank=True, null=True)),
                ('id_parcelle', models.ForeignKey(db_column='id_parcelle', default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='alignements', to='core.ruparcelle')),
            ],
            options={
                'db_table': 'ru_alignement',
            },
        ),
        migrations.CreateModel(
            name='RuRegle',
            fields=[
                ('id_regle', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(default='', max_length=50)),
                ('libelle', models.TextField(blank=True, null=True)),
                ('doc_urba', models.CharField(default='', max_length=50)),
                ('autorite', models.CharField(default='', max_length=50)),
                ('url_doc', models.CharField(default='', max_length=255)),
                ('standard_cnig', models.CharField(default='', max_length=50)),
                ('type_cnig', models.CharField(default='', max_length=50)),
                ('code_cnig', models.CharField(default='', max_length=50)),
                ('sous_code_cnig', models.CharField(default='', max_length=50)),
                ('cible', models.CharField(default='', max_length=50)),
                ('date', models.DateField(blank=True, null=True)),
                ('phrase_chatbot', models.TextField(blank=True, null=True)),
                ('type_cartads', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'ru_regle',
                'indexes': [models.Index(fields=['libelle'], name='idx_ru_regle_libelle'), models.Index(fields=['code'], name='idx_ru_regle_code')],
            },
        ),
        migrations.CreateModel(
            name='RuDetailAlignement',
            fields=[
                ('id_detail', models.IntegerField(primary_key=True, serialize=False)),
                ('valeur', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('id_alignement', models.ForeignKey(db_column='id_alignement', default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='details', to='core.rualignement')),
                ('id_regle', models.ForeignKey(db_column='id_regle', default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='details_alignement', to='core.ruregle')),
            ],
            options={
                'db_table': 'ru_detail_alignement',
            },
        ),
        migrations.CreateModel(
            name='RuDetail',
            fields=[
                ('id_detail', models.IntegerField(primary_key=True, serialize=False)),
                ('valeur', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('id_parcelle', models.ForeignKey(db_column='id_parcelle', default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='details', to='core.ruparcelle')),
                ('id_regle', models.ForeignKey(db_column='id_regle', default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='details', to='core.ruregle')),
            ],
            options={
                'db_table': 'ru_detail',
            },
        ),
        migrations.CreateModel(
            name='RuVoie',
            fields=[
                ('id_voie', models.IntegerField(primary_key=True, serialize=False)),
                ('libelle_long', models.TextField(blank=True, null=True)),
                ('libelle_court', models.TextField(blank=True, null=True)),
                ('code_voie_rivoli', models.CharField(default='', max_length=50)),
                ('code_voie_ville', models.CharField(default='', max_length=50)),
                ('voie_privee', models.SmallIntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ru_voie',
                'indexes': [models.Index(fields=['libelle_long'], name='idx_ru_voie_libelle_long')],
            },
        ),
        migrations.AddField(
            model_name='rualignement',
            name='id_voie',
            field=models.ForeignKey(db_column='id_voie', default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='alignements', to='core.ruvoie'),
        ),
    ]
