# Generated by Django 6.0.3 on 2026-03-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruparcelle',
            name='statut',
            field=models.CharField(choices=[('A_VALIDER', 'À valider'), ('ACTIVE', 'Active'), ('ARCHIVEE', 'Archivée')], default='A_VALIDER', max_length=20),
        ),
        migrations.AlterField(
            model_name='ruvoie',
            name='code_voie_rivoli',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='ruvoie',
            name='code_voie_ville',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='ruvoie',
            name='voie_privee',
            field=models.BooleanField(default=False),
        ),
    ]
