# Generated by Django 6.0.3 on 2026-03-21 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ruparcelle_statut_alter_ruvoie_code_voie_rivoli_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rualignement',
            name='id_voie',
            field=models.ForeignKey(db_column='id_voie', default=0, on_delete=django.db.models.deletion.PROTECT, related_name='alignements', to='core.ruvoie'),
        ),
        migrations.AlterField(
            model_name='rualignement',
            name='parite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ruvoie',
            name='libelle_court',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ruvoie',
            name='libelle_long',
            field=models.TextField(default='LIB_LONG'),
            preserve_default=False,
        ),
    ]
