# Generated by Django 6.0.3 on 2026-03-24 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_rualignement_id_voie_alter_rualignement_parite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rualignement',
            name='adresse_debut',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rualignement',
            name='adresse_fin',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rualignement',
            name='commune',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rualignement',
            name='suffixe_2_debut',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rualignement',
            name='suffixe_2_fin',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rualignement',
            name='suffixe_3_debut',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rualignement',
            name='suffixe_3_fin',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rualignement',
            name='suffixe_un_debut',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rualignement',
            name='suffixe_un_fin',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='ruparcelle',
            name='dep',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ruparcelle',
            name='identifiant',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ruparcelle',
            name='insee_com',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ruparcelle',
            name='insee_com_absorbee',
            field=models.CharField(blank=True, default='000', max_length=50),
        ),
        migrations.AlterField(
            model_name='ruparcelle',
            name='m2_dgfip',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ruparcelle',
            name='numero',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ruparcelle',
            name='section',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ruregle',
            name='autorite',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='ruregle',
            name='cible',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='ruregle',
            name='code_cnig',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='ruregle',
            name='doc_urba',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='ruregle',
            name='sous_code_cnig',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='ruregle',
            name='standard_cnig',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='ruregle',
            name='type_cnig',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='ruregle',
            name='url_doc',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='ruvoie',
            name='code_voie_rivoli',
            field=models.CharField(max_length=10),
        ),
    ]
