# Generated by Django 6.0.3 on 2026-03-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_rualignement_adresse_debut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruregle',
            name='type_regle',
            field=models.CharField(choices=[('PARCELLE', 'Parcelle'), ('ALIGNEMENT', 'Alignement')], default='PARCELLE', max_length=10),
        ),
        migrations.AlterField(
            model_name='ruvoie',
            name='code_voie_ville',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='ruvoie',
            name='voie_privee',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
