# Generated by Django 6.0.3 on 2026-03-27 15:11

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_ruregle_type_valeur'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ruparcelle',
            index=models.Index(django.db.models.functions.text.Lower('identifiant'), name='idx_ru_parcelle_identifiant_lw'),
        ),
        migrations.AddIndex(
            model_name='ruparcelle',
            index=models.Index(django.db.models.functions.text.Lower('insee_com_absorbee'), name='idx_ru_parcelle_insee_abs_lw'),
        ),
        migrations.AddIndex(
            model_name='ruparcelle',
            index=models.Index(django.db.models.functions.text.Lower('section'), name='idx_ru_parcelle_section_lw'),
        ),
        migrations.AddIndex(
            model_name='ruparcelle',
            index=models.Index(django.db.models.functions.text.Lower('numero'), name='idx_ru_parcelle_numero_lw'),
        ),
        migrations.AddIndex(
            model_name='ruregle',
            index=models.Index(django.db.models.functions.text.Lower('code'), name='idx_ru_regle_code_lw'),
        ),
        migrations.AddIndex(
            model_name='ruregle',
            index=models.Index(django.db.models.functions.text.Lower('libelle'), name='idx_ru_regle_libelle_lw'),
        ),
        migrations.AddIndex(
            model_name='ruregle',
            index=models.Index(django.db.models.functions.text.Lower('doc_urba'), name='idx_ru_regle_doc_urba_lw'),
        ),
        migrations.AddIndex(
            model_name='ruregle',
            index=models.Index(django.db.models.functions.text.Lower('autorite'), name='idx_ru_regle_autorite_lw'),
        ),
        migrations.AddIndex(
            model_name='ruregle',
            index=models.Index(django.db.models.functions.text.Lower('type_regle'), name='idx_ru_regle_type_regle_lw'),
        ),
        migrations.AddIndex(
            model_name='ruvoie',
            index=models.Index(django.db.models.functions.text.Lower('libelle_long'), name='idx_ru_voie_libelle_long_lw'),
        ),
        migrations.AddIndex(
            model_name='ruvoie',
            index=models.Index(django.db.models.functions.text.Lower('code_voie_ville'), name='idx_ru_voie_code_ville_lw'),
        ),
        migrations.AddIndex(
            model_name='ruvoie',
            index=models.Index(django.db.models.functions.text.Lower('code_voie_rivoli'), name='idx_ru_voie_code_rivoli_lw'),
        ),
    ]
