# Generated by Django 6.0.3 on 2026-03-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_demande_export', models.DateTimeField(auto_now_add=True, verbose_name='Date de la demande d export')),
                ('login_agent', models.CharField(max_length=150, verbose_name='Login de l agent')),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaire')),
                ('datetime_fin_export', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin de l export')),
                ('statut', models.CharField(choices=[('EN COURS', 'EN COURS'), ('EN ERREUR', 'EN ERREUR'), ('TERMINE', 'TERMINE'), ('ARCHIVE SUPPRIMEE', 'ARCHIVE SUPPRIMEE')], default='EN COURS', max_length=30, verbose_name='Statut de l export')),
                ('nom_du_fichier', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom du fichier')),
                ('poids_du_fichier', models.CharField(blank=True, max_length=100, null=True, verbose_name='Poids du fichier')),
                ('nombre_de_parcelles', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de parcelles')),
                ('nombre_d_alignements', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre d alignements')),
                ('nombre_de_regles', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de regles')),
                ('nombre_de_details', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de details')),
            ],
        ),
    ]

