# Generated by Django 6.0.3 on 2026-03-27 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _split_auth_model():
    app_label, model_name = settings.AUTH_USER_MODEL.split('.')
    return app_label, model_name


def forwards_copy_login_to_agent(apps, schema_editor):
    RuExport = apps.get_model('backoffice', 'RuExport')
    user_app_label, user_model_name = _split_auth_model()
    UserModel = apps.get_model(user_app_label, user_model_name)

    username_to_id = {
        row['username']: row['id']
        for row in UserModel.objects.values('id', 'username')
    }

    for export in RuExport.objects.exclude(login_agent__isnull=True).exclude(login_agent=''):
        user_id = username_to_id.get(export.login_agent)
        if user_id:
            export.agent_id = user_id
            export.save(update_fields=['agent'])


def backwards_noop(apps, schema_editor):
    # Reverse data copy intentionally left empty.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0003_auth_case_insensitive_sort_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ruexport',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exports', to=settings.AUTH_USER_MODEL, verbose_name='Agent'),
        ),
        migrations.RunPython(forwards_copy_login_to_agent, backwards_noop),
        migrations.RemoveField(
            model_name='ruexport',
            name='login_agent',
        ),
    ]
